title: Hello, world! Adel Akbar
description: > # this means to ignore newlines until "baseurl:"
  I code, play games, trade and a bunch more. This blog is to document all the crazy that I get upto and just thoughts in general.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://itsadel.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Adel Akbar # add your name
author-img: david-freeman.jpg # add your photo
about-author: I code, play games, trade and a bunch more. # add description
social-twitter: adelakbarhere # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: itsAdel # add your Github handle
social-linkedin: adel.akbar # add your Linkedin handle
social-email: adelakbarhere@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
